### ISSUE TITLE
Update graphic layout (all views without login required)

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#146]
Propose a new graphic layout

**Comment by PatrykMoga** [comment]
Maybe we could start using Angular?

**Comment by WTobor** [comment]
It id not on the scope. We can make a research and use e.x. Blazor. But in scope of this task is only preparing new layout (styles, graphics).

**Comment by WTobor** [comment]
Views:
- About
- Home
- Prizes
- Sponsors
- Results
- Contact
- Login
- Register
- Privacy
- Rules

**Comment by darek-grund** [comment]
Current status:
- [x] About
- [x] Home
- [x] Prizes
- [x] Sponsors
- [ ] Results
- [x] Contact
- [x] Login
- [x] Register
- [x] Privacy
- [x] Rules
- [ ] Error
