### ISSUE TITLE
Review and update API validation

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#153]
Review API validation - ensure that there is no possibility to hack it (answer before window opening period)
Add/update tests

Add some easter eggs (@patrikulus -give few examples)

**Comment by WTobor** [comment]
@smiechuskce is there any progress?

**Comment by smiechuskce** [comment]
Actually, no, it needs quite a lot of time. I'm trying different tools but currently - no errors according to the API.

**Comment by WTobor** [comment]
You can use https://swagger.io/tools/swagger-inspector/, too ;)
