### ISSUE TITLE
Integrate code quality tools in pipeline

### ISSUE THREAD

**Issue by patrikulus** [DevAdventCalendar/DevAdventCalendar#159]
e.g. SonarQube, dockerfilelint etc.

**Comment by WTobor** [comment]
We already have Stylecop and FxCop rulesets, could you use it?

**Comment by WTobor** [comment]
I can see that it also analyzes branches and decorates Pull requests, so it looks good :)

**Comment by WTobor** [comment]
I prepared project https://sonarcloud.io/organizations/devadventcalendar/projects
