### ISSUE TITLE
Remove old styles and images

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#172]
**To Reproduce**
Open the repository

**Current behavior**
There are old styles and images in the repository (except theme-2019 folder)

**Expected behavior**
There are no unused styles and images in the repository (except theme-2019 folder)

**Comment by sonakollarova5** [comment]
Can I work on this issue?

**Comment by WTobor** [comment]
Yes, of course :)
Remember to create branch from the `develop` branch.
Please add @darek-grund as a reviewer to Pull Request.

**Comment by WTobor** [comment]
@sonya323 - do you still want to work on this issue? :)

**Comment by sonya323** [comment]
Finally, I choose for my subject at school different issue. So, this one is than free. I'm sorry.

**Comment by WTobor** [comment]
Thanks for the update!
