### ISSUE TITLE
Unable to register new account

### ISSUE THREAD

**Issue by darek-grund** [DevAdventCalendar/DevAdventCalendar#203]
**To Reproduce**
1. Go to https://devadventcalendar.pl/Account/Register
2. Fill registration form
3. Click "Zarejestruj"
![image](https://user-images.githubusercontent.com/46841992/67698502-c4061400-f9aa-11e9-9b4c-ead6b0a4fc59.png)

**Current behavior**
After submitting form, user sees error "404: Unable to find page". But it seems that new account has been created, but no confirmation email has been sent.

**Expected behavior**
1. After submitting form user sees confirmation page, not 404 page.
2. Email with comfirmation link is sent, so user is able to confirm his email is correct

**Comment by Oliweirdo** [comment]
If we run the application and try to register, this is what we see 
![error](https://user-images.githubusercontent.com/29609457/69414014-2df7ac00-0d12-11ea-87cc-a7b4a14c2a13.png)
When we disable parts of code responsible for sending emails, The confirmation page appears.  

Now I`m working on it.

**Comment by WTobor** [comment]
you probably need to add parameter _UriKind.Relative_ to new _URI()_

**Comment by WTobor** [comment]
found the reason: there is a need to configure in `appsettings.development.json` the email account to send emails (it should be described in `readme` file)
