### ISSUE TITLE
Update layout for calendar main page

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#220]
Update calendar layout to show 4 rows:
- day 1 - 7 (7 days) - week 1
- day 8 - 14 (7 days) - week 2
- day 15 - 21 (7 days) - week 3
- days 22-24 (3 days) - 3 extra days

**Comment by darek-grund** [comment]
PR: https://github.com/DevAdventCalendar/DevAdventCalendar/pull/226
