### ISSUE TITLE
User name do not change after changing email address

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#246]
**To Reproduce**
1. Create new account with email address '1'
2. Confirm created account and go to the user account panel
3. User name = address email for which account was created
4. Change email address and confirm operation. Email address '2'

**Current behavior**
Visible user name = email address '1'

**Expected behavior**
After changing email address from '1' to '2' user name should also change into second - changed email address. 

**Screenshots**

**Additional context**

**Comment by WTobor** [comment]
In new logic UserName not equals Email address, so this is out of scope
