### ISSUE TITLE
Screen with information that answer was correct should be better adjusted + some options should be added

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#250]
**To Reproduce**
1. Find slot with the question for which correct answer has been added
2. Answer the question - answer should be correct and press send
3. Observe the screen

**Current behavior**
Text 'odpowiedz poprawna' is to much on the left. There is no option visible, to go back to the main menu, or go to your results
![image](https://user-images.githubusercontent.com/57844124/69885293-b8c14380-12dc-11ea-888b-09381a0581b9.png)

**Expected behavior**
At confirmation screen, text should be better adjusted, there is to much which space around.
Some options should be added for this page, like:
- go to the main menu,
- go and see your results,
- etc. 

**Screenshots**

**Additional context**

**Comment by WTobor** [comment]
Go to main menu button should be enought
