### ISSUE TITLE
Error 404 after clicking on day for which test was finished earlier

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#253]
**To Reproduce**
1. Create test for one day
2. Mark this test 'zakończ test wcześniej'
3. Go to the list of questions - this question is greyed out
![image](https://user-images.githubusercontent.com/57844124/69886361-e8bf1580-12e1-11ea-8173-29f3bfcb71cc.png)

4. Click on that day - see the results

**Current behavior**
![image](https://user-images.githubusercontent.com/57844124/69886323-b0b7d280-12e1-11ea-9053-844aa9a0f44e.png)

**Expected behavior**
Error 404 should not be visible. Some information that this test was finished earlier should be visible

**Screenshots**

**Additional context**

**Comment by WTobor** [comment]
we don't want to finish test earlier - @patrikulus please check if it works correctly for normal tests (not finished earlier)

**Comment by WTobor** [comment]
We have no scenario with finishing test earlier - but this changes can be made, maybe we will use this solution in future

**Comment by WTobor** [comment]
@szrtGreg could you please check if that error still occures?

**Comment by szrtGreg** [comment]
Sure

**Comment by szrtGreg** [comment]
Error not occures. Doing same procedure as described below I get:

![obraz](https://user-images.githubusercontent.com/27915290/94799812-02d6f200-03e4-11eb-8b87-db256b400ecc.png)

![obraz](https://user-images.githubusercontent.com/27915290/94799843-0ff3e100-03e4-11eb-98bb-be5e13401ef4.png)

We see that URL is slightly changed that it was before. And it works as expected. Issue can be closed

**Comment by WTobor** [comment]
Let's try with a test that does not exist or you didn't answer?
