### ISSUE TITLE
Lack of icon 'Week 4' at the page next to the questions

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#254]
**To Reproduce**
1. Go to the page: https://dev.devadventcalendar.pl/
2. There are visible icons week 1,2,3 but week 4 is not visible

**Current behavior**
Lack of icon 'Week 4'

**Expected behavior**
Icon Week 4 should be visible.

**Screenshots**

**Additional context**

**Comment by WTobor** [comment]
It is not a bug ;)
