### ISSUE TITLE
Unable to login with Facebook in Edge

### ISSUE THREAD

**Issue by jkolonko** [DevAdventCalendar/DevAdventCalendar#262]
**To Reproduce**
1. Go to 'https://www.devadventcalendar.pl/Account/Login' in Edge
2. Click on 'Facebook'

**Current behavior**
You are redirected to Facebook page with error message:
URL blocked: This redirect failed because the redirect URI is not white-listed in the app's client OAuth settings. Make sure that the client and web OAuth logins are on and add all your app domains as valid OAuth redirect URIs.
After pressing OK (then and in the subsequent dialog), another error message:
Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later.

**Expected behavior**
User is able to log in 

**Additional context**
Occures in both MSHTML-based edge and Chromium-based Edge

Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363
(Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363)

Version 80.0.334.4 (Official build) dev (64-bit)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3965.0 Safari/537.36 Edg/80.0.334.4

**Comment by jkolonko** [comment]
Workaround exists: Use another browser or another sign-in provider.

**Comment by smiechuskce** [comment]
It's worse. I am unable to sign in using also Chrome and Firefox. Same result.

**Comment by WTobor** [comment]
@szrtGreg please ensure it works on Chrome, Edge, Mozilla and IE 😃

**Comment by szrtGreg** [comment]
Yes, I am not able to log in using Facebook using FF. Investigating...

**Comment by szrtGreg** [comment]
@smiechuskce  @jkolonko @WTobor  Dear I was able to log in using Facebok on FF and Edge. Problem you mentined is with prefix 'www' its not allowed log in with providers using that prefix. For now whole DAC works without 'www' and its correct behaviour. Even when you type devadventcalendar on google it redirects you to: https://devadventcalendar.pl/ ane when you want to log in it redirects you to: https://devadventcalendar.pl/Account/Login

**Comment by szrtGreg** [comment]
For now I will check if you could log in using other providers

**Comment by szrtGreg** [comment]
Tested. Looks correct.
