### ISSUE TITLE
Error page  does not exist

### ISSUE THREAD

**Issue by olekstomek** [DevAdventCalendar/DevAdventCalendar#264]
**Is your feature request related to a problem? Please describe.**
Error page doesn't work. 
Go to e.g. https://devadventcalendar.pl/test404, you get

> Nie można znaleźć tej strony na devadventcalendar.plNie znaleziono strony internetowej pod adresem https://devadventcalendar.pl/test404
> HTTP ERROR 404

**Describe the solution you'd like**
E.g. https://github.com/DevAdventCalendar/DevAdventCalendar/issues/32

**Describe alternatives you've considered**
Redirect to main page.

**Additional context**

![image](https://user-images.githubusercontent.com/26818304/69988066-28376d00-1541-11ea-940e-6426557215cc.png)

**Comment by WTobor** [comment]
duplicated in #253

**Comment by KrystianKolad** [comment]
Hi, is it up for grab?

**Comment by olekstomek** [comment]
> Hi, is it up for grab?

Yes, this and https://github.com/DevAdventCalendar/DevAdventCalendar/issues/253 have open status.

**Comment by WTobor** [comment]
@KrystianKolad yes! Please assign to it ;)

**Comment by KrystianKolad** [comment]
@WTobor I don't think I can assign myself to it, can you assign me? ;)

**Comment by WTobor** [comment]
@KrystianKolad done :)
