### ISSUE TITLE
Wrong answer to the question - showing our answer in the message

### ISSUE THREAD

**Issue by olekstomek** [DevAdventCalendar/DevAdventCalendar#266]
**Is your feature request related to a problem? Please describe.**
After a wrong answer, only the message saying that the answer is wrong is printed. 

**Describe the solution you'd like**
Showing our answer (what we entered) can make sure that we did not make a mistake in the word (typos).

**Describe alternatives you've considered**
Not applicable.

**Additional context**
Not applicable.

**Comment by WTobor** [comment]
@olekstomek - maybe this is a great task for you ❓

**Comment by olekstomek** [comment]
> @olekstomek - maybe this is a great task for you ❓

@WTobor I don't write in C#, I don't have an environment and configuration for it. I focus on other technology and devote my time to it.
P.S. I regret that it's not Java. :)

**Comment by bananbe** [comment]
Hello @WTobor , I would like to take a look at this issue :)

**Comment by WTobor** [comment]
Great :) Let me know if I can help

**Comment by bananbe** [comment]
I may need some help :) I run project locally and also in Docker, but in both cases result is the same. I'm logging as a test user, and even though login is successful, the user is not authenticated and `NameIdentifier` claims are `null`. Have I forgot about something, so login is not working correctly for me?

**Comment by szrtGreg** [comment]
Good Morning @bananbe if you want, we can have quick chat to help you with project run.

**Comment by WTobor** [comment]
@bananbe what browser are you using? It should work on Firefox.

**Comment by bananbe** [comment]
I was trying opening this on Chrome, but switching to Firefox worked like a charm :) Thanks @WTobor!

@szrtGreg thanks for the proposition, but right now it looks like that I can handle this further.

**Comment by WTobor** [comment]
Apparently, we have an issue with Chrome - we need to investigate that. Could you please add a new Bug with screenshots?
