### ISSUE TITLE
Automatically unlocking the window without refreshing the page manually

### ISSUE THREAD

**Issue by olekstomek** [DevAdventCalendar/DevAdventCalendar#267]
**Is your feature request related to a problem? Please describe.**
Automatically unlocking the window without refreshing the page manually if the user has this page open in browswer. In the present case, the window automatically unlocks and is clickable at 8 PM.

**Describe the solution you'd like**
In the present case, the window automatically unlocks and is clickable at 8 PM.

**Describe alternatives you've considered**
Automatic page refresh (currently at 8 PM).

**Additional context**
Not applicable.

**Comment by WTobor** [comment]
@olekstomek - maybe you want to implement such a logic? :)

**Comment by olekstomek** [comment]
> @olekstomek - maybe you want to implement such a logic? :)

@WTobor I don't write in C#, I don't have an environment and configuration for it. I focus on other technology and devote my time to it.
P.S. I regret that it's not Java. :)

**Comment by Oliweirdo** [comment]
I think,  It could be something like combine html meta tag and JS function, for example:

```
<meta name="Pragma" content="no-cache;">

<script language="javascript" type="text/javascript">
function reloadAt20{
var d = new Date();
var time = d.getHours();
if(time==20{location.reload();}
}
window.setInterval("reloadAt20", 1000);
</script>

```
Just add to razor page. What you think?

**Comment by WTobor** [comment]
maybe something like https://stackoverflow.com/a/58866528?

**Comment by olekstomek** [comment]
I think you don't need reload all page, but only part of page, section of page. 
https://api.jquery.com/load/

**Comment by WTobor** [comment]
@Oliweirdo are you still working on this issue? :)

**Comment by Oliweirdo** [comment]
@WTobor  Yes, currently  I`m looking for solution to not use JQuery  :)
