### ISSUE TITLE
Addition of a button to proceed to all puzzles on the completed puzzle page

### ISSUE THREAD

**Issue by olekstomek** [DevAdventCalendar/DevAdventCalendar#268]
**Is your feature request related to a problem? Please describe.**
Instead of clicking _back_ in the browser, the button moves to the section. Clicking on the logo takes you to the top of the page.

**Describe the solution you'd like**
Instead of clicking _back_ in the browser, move to the puzzle windows section (not to top of main page) by button.

**Describe alternatives you've considered**
Moving to a random or next unfinished puzzle. If all puzzles completed, move to the section of all puzzles as described above.

**Additional context**
![image](https://user-images.githubusercontent.com/26818304/70393153-8b188080-19e7-11ea-9f14-a11070807281.png)

**Comment by Oliweirdo** [comment]
Can I ask - where  the puzzle windows section is placed in solution? I want to add href in the button  for move user to proper page, but I can`t find it :(

**Comment by WTobor** [comment]
Of course :) view for the particular puzzle is here  https://github.com/DevAdventCalendar/DevAdventCalendar/blob/develop/src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Test/Index.cshtml

**Comment by Oliweirdo** [comment]
Thank You so much!
I have the last question, where  is the target view? I mean, where is  the puzzle windows section?

**Comment by WTobor** [comment]
View with al puzzles is available here https://github.com/DevAdventCalendar/DevAdventCalendar/blob/develop/src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Home/Index.cshtml :)
