### ISSUE TITLE
Fix the vulnerabilities in SonarCloud (SonarCloud Quality Gate failed.) 

### ISSUE THREAD

**Issue by Oliweirdo** [DevAdventCalendar/DevAdventCalendar#277]
**Current behavior**
There are two vulnerabilities   in files [Admin/_Layout.cshtml](src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Admin/_Layout.cshtml)  and [Shared/_Layout.cshtml](src/DevAdventCalendarCompetition/DevAdventCalendarCompetition/Views/Shared/_Layout.cshtml)

**Additional context**
this is the reason why we should fix this.  [sonarcloud](https://sonarcloud.io/organizations/devadventcalendar-1/rules?open=Web%3AS5148&rule_key=Web%3AS5148)

**Comment by KrystianKolad** [comment]
Hi, is it up for grab?

**Comment by WTobor** [comment]
@Oliweirdo is it?

**Comment by Oliweirdo** [comment]
Actually it`s  fixed. Sorry, I forgot to close this issue
