### ISSUE TITLE
AdBlock blocks snowfall.jquery.js

### ISSUE THREAD

**Issue by lkurzyniec** [DevAdventCalendar/DevAdventCalendar#284]
**To Reproduce**
1. Enter to home page

**Current behavior**
AdBlock blocks one of the main js file, which makes impossible to enter the home screen.

**Expected behavior**
Stop blocking `snowfall.jquery.js` file. I don't know how, there should be a way.

**Screenshots**
![image](https://user-images.githubusercontent.com/5943484/77233014-ea6c5c00-6ba4-11ea-8206-105439952192.png)

**Comment by WTobor** [comment]
@lkurzyniec - which browser are you using?

**Comment by lkurzyniec** [comment]
Chrome

**Comment by darek-grund** [comment]
Resolved in PR https://github.com/DevAdventCalendar/DevAdventCalendar/pull/310
