### ISSUE TITLE
develop as a default branch

### ISSUE THREAD

**Issue by lkurzyniec** [DevAdventCalendar/DevAdventCalendar#289]
![image](https://user-images.githubusercontent.com/5943484/77257489-ead42800-6c74-11ea-8930-fc1726cdd1bb.png)

**Comment by lkurzyniec** [comment]
@WTobor one more enhancement.

**Comment by WTobor** [comment]
Yes, I can do this - but  was always afraid of consequences ;p
![image](https://user-images.githubusercontent.com/22730914/77347761-a1e5a780-6d38-11ea-935d-814368f65096.png)

**Comment by lkurzyniec** [comment]
I already changed it for my fork of your repo.
![image](https://user-images.githubusercontent.com/5943484/77541246-b050d200-6ea4-11ea-9ab2-e2b00b921db7.png)

**Comment by WTobor** [comment]
Your fork, your repo, your rules. You don't have Pull Requests :) But now finally we will have 0 PRs, so I can do magic :D
