### ISSUE TITLE
Default user in application didn't work

### ISSUE THREAD

**Issue by Jumpeq** [DevAdventCalendar/DevAdventCalendar#296]
We can't login to user: devadventcalendar@gmail.com
Default password isn't correct

**Comment by WTobor** [comment]
Probably the _StringHasher.Salt_ (`appsettigs.Development.json`) has changed, so there is a need to update the password (create new migration).

Moreover, we should add info in README about default admin user with login `devadventcalendar@gmail.com` and default password `P@ssw0rd`
