### ISSUE TITLE
CalculateResult View isn't accessible

### ISSUE THREAD

**Issue by Jumpeq** [DevAdventCalendar/DevAdventCalendar#306]
View https://localhost:44301/Admin/CalculateResults isn't accessible

![image](https://user-images.githubusercontent.com/33371237/81435922-e1414980-9168-11ea-9812-509054d790f4.png)

"Kodowanie znaków dokumentu czystotekstowego nie zostało zadeklarowane. Podczas wyświetlania tego dokumentu w niektórych konfiguracjach przeglądarki niektóre znaki spoza zakresu US-ASCII (o ile występują) mogą wyglądać nieprawidłowo. Kodowanie znaków pliku musi być zadeklarowane w protokole przesyłania, albo plik musi używać znacznika kolejności bajtów jako sygnatury kodowania."

**Comment by WTobor** [comment]
Please delete _CalculateResult_ method and button in Admin view
