### ISSUE TITLE
Fix og:image resolution to fit for Messanger

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#314]
**To Reproduce**
1. Send link to www.devadventcalendar.pl on Messager

**Current behavior**
The full logo is not visible 
![image](https://user-images.githubusercontent.com/22730914/83975289-6d26cc80-a8f3-11ea-952e-e7ed93b050af.png)

**Expected behavior**
The full logo is visible

**Comment by darek-grund** [comment]
I'm working on it
