### ISSUE TITLE
Fix swagger documentation

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#317]
**To Reproduce**
1. Go to endpoint /swagger ex. https://devadventcalendar.pl/swagger

**Current behavior**
Documentation does not work, the name of the definition is QuickApp
![image](https://user-images.githubusercontent.com/22730914/84008268-e1a05080-a971-11ea-8743-7aff835440e8.png)

**Expected behavior**
Swagger documentation is working, the name of the definition is DevAdventCalendar

**Comment by WTobor** [comment]
It is almost ok :)

We should add for every controller
``[Route("[controller]/[action]")]``
and remove routes for endpoints that are named the same as methods

**Example**:
do not remove attribute in Home Controller for endpoint
``[Route("11111100011")]
public ActionResult Surprise()``
but remove for endpoints like
``[Route(nameof(About))]
public ActionResult About()``

**Comment by WTobor** [comment]
And there is still name of the definition **QuickApp** ;p
![image](https://user-images.githubusercontent.com/22730914/86210317-af4ed100-bb74-11ea-90c0-ec9f56fe7372.png)

**Comment by WTobor** [comment]
@szrtGreg  could you help with that? look at my last and one before last comment

**Comment by szrtGreg** [comment]
sure, I will have a look

**Comment by szrtGreg** [comment]
I did some tests - different variations like: 
1) added to controller [Route("[controller]/[action]")]
2) added to controller only [Route("[controller]")]
3) Adding Attribute to methods like:  [Route(nameof(Error))]
4) Adding Attrribute to methods like:  [Route("Error")]
5) Or even remove Route attribute at all

In all scenario application was not rendered correctly. My assumotion is there is overlaping configuration in Startup file

![obraz](https://user-images.githubusercontent.com/27915290/92093690-eab78700-edd3-11ea-8d87-15a4d63bf426.png)

That leads me to a assumptions that "add [Route("[controller]/[action]")] for every controller" is already implemented?

Moreover with current setup for About method
![obraz](https://user-images.githubusercontent.com/27915290/92094348-a24c9900-edd4-11ea-97d2-a97db69e6633.png)

We see that url looks like that:
![obraz](https://user-images.githubusercontent.com/27915290/92094506-d0ca7400-edd4-11ea-9e6b-1f15604830f5.png)

However when we delete route attribute:
![obraz](https://user-images.githubusercontent.com/27915290/92094628-f35c8d00-edd4-11ea-9ec8-e6f9016d426e.png)

Url looks like
![obraz](https://user-images.githubusercontent.com/27915290/92094731-0ec79800-edd5-11ea-8732-c14cda49d00a.png)

Which is probably not desired.

Please tell me if I am going right direction. Thanks

**Comment by WTobor** [comment]
@szrtGreg yes, we want to have url `localhost/About`, not `localhost/Home/About` - so for HomeController we want Route attribute

If I understand correctly, we don't need attributes in all other controllers - so please remove it ;)

**Comment by szrtGreg** [comment]
I am ready for PR however one more little question: For what name we change definition"QuickApp"?

**Comment by WTobor** [comment]
@szrtGreg - DevAdventCalendar :)
