### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by Mejtika** [DevAdventCalendar/DevAdventCalendar#333]
**Is your feature request related to a problem? Please describe.**
We should think about adding integration tests that will increase both our test coverage and protection against regression.

**Describe the solution you'd like**
At the beginning, we can cover the service layer with integration tests.

**Comment by smiechuskce** [comment]
Good idea, I'd like to get involved in this after API security tests.

**Comment by WTobor** [comment]
@Mejtika please updare README to describe both types of tests
