### ISSUE TITLE
Problem with subscribe for notification in user profile

### ISSUE THREAD

**Issue by szrtGreg** [DevAdventCalendar/DevAdventCalendar#336]
**To Reproduce**
    1. Create account with email address '1'
    2. Confirm email
    3. Login to account with email address '1'
    4. 'Twoje konto' -> switch to yes 'Chce otrzymywac notyfikacje'
    5. 'Zapisz'

**Current behavior**
Internal Server Error

**Expected behavior**
Application should work properly.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/27915290/87150391-3b1dd700-c2b2-11ea-8c81-e143ca0e22a1.png)
![error](https://user-images.githubusercontent.com/27915290/87151913-fe9faa80-c2b4-11ea-9afb-dc9248372737.jpg)

**Additional context**
Probably some typo in Manage Controller

**Comment by WTobor** [comment]
You need to set in `appsettings` `EmailNotification` configuration
