### ISSUE TITLE
API review - email confirmation

### ISSUE THREAD

**Issue by smiechuskce** [DevAdventCalendar/DevAdventCalendar#348]
**Steps to reproduce**

Using the dev site.

1. Go to address, for example: https://dev.devadventcalendar.pl/Account/ConfirmEmail?userId=1&code=1234564564564564df6sadasdsa
2. Observe HTTP response.

**Current behavior**

A HTTP 500 error will be returned with stacktrace if code/token is not valid. 
Also, the GET method is being used to update state.

**Expected behavior**

Client should be redirected to the Error view.
Would be better to use POST/PUT instead of GET.

**Comment by szrtGreg** [comment]
I did tests. To Resolve half of this issue. I need to find out how catch exception and redirect to user error page.

![obraz](https://user-images.githubusercontent.com/27915290/89119622-0a475100-d4b0-11ea-9851-e95e4ce38d64.png)
