### ISSUE TITLE
Change existing users UserNames

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#353]
All previous user has UserName = Email. We should find the solution to let them set UserName (once)

Maybe add some flag in Db `AllowChangeUserName`?

**Comment by smiechuskce** [comment]
Is there a reason of limiting users to change their names just once?

**Comment by WTobor** [comment]
for now yes - we need to keep it unique identifier visible in the list of results. We will not support emails. As you remember, previously we were using email and we were formatting it to w**a@o**.pl (RODO etc).
If you have other ideas - please describe :)
Remember that for now, we are calculating results once per week. We want to have the same nickname in all tables of results; If it's ok (we are getting login by id) - then changing login in the middle of the contest may not be a problem :)

**Comment by smiechuskce** [comment]
Ok, I forgot about the current results calculation logic. It looks good, though. Or maybe we can allow user to change his name not once for all but once per the actual competition. What do you think? I don't see any potential issues with that kind of solution.

**Comment by WTobor** [comment]
I don't see the privilege of changing the name once per competition. Allow to change at any time or block it.
Of course, we need to ensure that changing the name will not break anything.
But from a business perspective - why to change login? Probably that feature will not be used many times.

**Comment by smiechuskce** [comment]
So, let's just allow to change nickname at any time (because, why not) but we have to be sure, that everywhere in the code there are references to the user by ID/email, not by UserName.

**Comment by WTobor** [comment]
@smiechuskce what about existing users? generate their user names automatically?

**Comment by smiechuskce** [comment]
> @smiechuskce what about existing users? generate their user names automatically?

I think, it's a good idea. Would the repeated email be a good basic user name?

**Comment by WTobor** [comment]
@smiechuskce no, we don't want to show the email in the results table. We can use the first part of the email (before @) and add sth in case of duplication

**Comment by smiechuskce** [comment]
> @smiechuskce no, we don't want to show the email in the results table. We can use the first part of the email (before @) and add sth in case of duplication

Yeah, I meant, the shortened emails. I am not sure about the whole first part of an email. Isn't it nearly the same as showing the full email? I'm thinking if there are other solutions that make sense...

**Comment by WTobor** [comment]
@smiechuskce you are right... maybe generate a random string?

**Comment by smiechuskce** [comment]
> @smiechuskce you are right... maybe generate a random string?
Technically, that'd work quite well but wouldn't look good on a results list ;) Unless we won't change anything and still show the shortened emails with dots on a list instead of user names. Optional, we could ask user to change his user name after his first login.

**Comment by smiechuskce** [comment]
> > @smiechuskce you are right... maybe generate a random string?

Technically, that'd work quite well but wouldn't look good on a results list ;) Unless we won't change anything and still show the shortened emails with dots on a list instead of user names. Optional, we could ask user to change his user name after his first login.
