### ISSUE TITLE
Display player his own stats

### ISSUE THREAD

**Issue by BlackMorzan** [DevAdventCalendar/DevAdventCalendar#366]
**Is your feature request related to a problem? Please describe.**
Allowing player to see his own stats might be a nice quality of life improvement. 

**Describe the solution you'd like**
The solution might be creating another tab in player profile where statistics are displayed. One way to implement this might be gathering data from database on entering tab.

**Additional context**
This feature combined with **Display stats of all players** will allow player to compare his achievements to other participants and hopefully motivate him to fight harder for rewards.    

**Example**
This is simple way to display player statistics:
"You answered 3'rd question on 4'th try at 05.12 8:30 PM"
"You did not answered 4'rd question yet. You already tried 6 times"
"You did not answered 5'th question yet. It will be your 1'st try!"

**Comment by WTobor** [comment]
@BlackMorzan please write down examples of stats :)
