### ISSUE TITLE
Add tests that will cover Google Calendar integration

### ISSUE THREAD

**Issue by Mejtika** [DevAdventCalendar/DevAdventCalendar#400]
**Is your feature request related to a problem? Please describe.**
We have to add tests that will cover new integration.

**Describe the solution you'd like**
We have to cover GoogleCalendarService and ManageController.
To mock HttpClient we could use those methods:
https://dev.to/gautemeekolsen/how-to-test-httpclient-with-moq-in-c-2ldp
https://anthonygiretti.com/2018/09/06/how-to-unit-test-a-class-that-consumes-an-httpclient-with-ihttpclientfactory-in-asp-net-core/

**Comment by Reisclef** [comment]
I'd really like to do this. I've mocked HttpClient with Moq as well, so if you'd like me to do this issue, please assign me, or let me know here. :)
