### ISSUE TITLE
Wrong icon for /polityka.pdf and /regulamin.pdf pages

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#419]
**To Reproduce**
1. Go to https://devadventcalendar.pl/polityka.pdf and https://devadventcalendar.pl/regulamin.pdf

**Current behavior**
The icon contains an old logo

**Expected behavior**
The icon contains a new logo

**Screenshots**
![image](https://user-images.githubusercontent.com/22730914/97777437-764d5a00-1b70-11eb-9853-5177459cec9b.png)

**Additional context**

**Comment by szrtGreg** [comment]
When you want to bookmark DAC (and you WANT to :) ) its still old logo

![obraz](https://user-images.githubusercontent.com/27915290/98441438-947e0180-20fe-11eb-9eaf-4115749f2472.png)
