### ISSUE TITLE
Update partners imgs in calendar view

### ISSUE THREAD

**Issue by WTobor** [DevAdventCalendar/DevAdventCalendar#433]
In calendar view (after login) there should be visible weekly partners logo with url (the same as in Partners view)
- week 1 SoftServe
- week 2 CShark
- week 3 SpyroSoft

In calendar view (after login) there should be visible main partner logo with url (the same as in Partners view) above the calendar view - Incat

**Comment by szrtGreg** [comment]
I created sponsors:
![obraz](https://user-images.githubusercontent.com/27915290/99538759-b3597f00-29ad-11eb-947b-d5554fffd56b.png)


What size would be for a main sponsor? bigger, smaller or do it other way?

![obraz](https://user-images.githubusercontent.com/27915290/99538871-db48e280-29ad-11eb-8544-61705d5cdfd0.png)

**Comment by WTobor** [comment]
it looks good - maybe lower the bottom margin :) The text should "partner główny"
