### ISSUE TITLE
Lack of email uniqueness check

### ISSUE THREAD

**Issue by Mejtika** [DevAdventCalendar/DevAdventCalendar#440]
**To Reproduce**
1. Go to 'https://dev.devadventcalendar.pl/Account/Register'.
2. Register new user (they'll be an error due to wrong EmailSender config, but the user will be created).
3. Register new user again with the previous one email.

**Current behavior**
Currently, only the username is checked for duplication. Multiple users can be registered using the same email address.

**Expected behavior**
The email should be also checked for uniqueness.

**Screenshots**
![image](https://user-images.githubusercontent.com/28907927/99509809-8cd41d80-2986-11eb-8176-6f93bd79f5b7.png)

**Comment by smiechuskce** [comment]
It looks like a bug, indeed. It also gives us a field to think about the real uniqueness of the user. He can register using the same email address but he can also choose different email address(es) and different name(s) to register them and thus make more chance to win.

@WTobor what do you think?

**Comment by WTobor** [comment]
@smiechuskce  we cannot check if the user created a new account with a different username and email. But for sure we can not allow creating another account for the same email
