### ISSUE TITLE
Results - incorrect result in the first position in 2nd week

### ISSUE THREAD

**Issue by olekstomek** [DevAdventCalendar/DevAdventCalendar#494]
**To Reproduce**
1. Go to https://devadventcalendar.pl/Results/Index
2. Click on 'Tydzień 2' tab

**Current behavior**
Incorrect result in the first position. 9 answers in 7 days. 

**Expected behavior**
Correct result

**Screenshots**
![image](https://user-images.githubusercontent.com/26818304/102243894-fb5fb900-3efb-11eb-9c1e-36f0bfd97695.png)

**Comment by WTobor** [comment]
@olekstomek thank you for raising an issue. We are aware of that - working on it.
